version: "3.8"

services:
  db:
    container_name: "wordpress-db"
    image: mariadb:latest
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    
  wordpress:
    depends_on:
      - db
    container_name: "wordpress-wp"
    image: wordpress:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  adminer:
    depends_on:
      - db
    container_name: "adminer-app"
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"
